---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fnserver-lua
  namespace: istio-system
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      portNumber: 80
      listenerType: GATEWAY
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.lua"
    filterConfig:
      inlineCode: |
        function envoy_on_response(response_handle)
          body_size = response_handle:body():length()
          response_handle:headers():add("response-body-size", tostring(body_size))
          response_handle:headers():add("tainted-by", "chanwit")
        end

